### PR TITLE
[rwt_app_chooser] support app args

### PR DESCRIPTION
**Pull request by sktometometo**
Support args when start an app.

### CODE REVIEW

**Comment by Affonso-Gui** [comment]
I am generally against increasing the number of prompts. I believe that one of the main strengths of the rwt_app_chooser is its ability to be used on mobile devices, and I don't think that emulating a text-heavy CLI interface is doing any good for that.

Besides that, this implementation also has several points that need to be more thoroughly discussed:
1. How is the user supposed to know what type of arguments and value ranges are supported?
1. What should be the default behavior on parse errors? Ignore the prompt and launch with default values anyways does not seem appropriate.
1. Is this safe regarding injection and other security leaks?

Normally, I would suggest to implement different app instances with different argument values.
If this is impractical due to a wide range of possible values, then I guess we should consider implementing more extensive arg support or consider other client interfaces for the app_manager server.

**Comment by sktometometo** [comment]
It is impractical to implement different app instances for different args because some app can take args with variable length.　The number of applications will be a number of combinations.

Main reason of "text-heavy CLI interfaces" for app args is that [args field of StartApp service](https://github.com/PR2/app_manager/blob/debed0fda805d32ee5a9c28325080ea4ec01acc7/srv/StartApp.srv#L3) is already extensive and there is still no interface for app_manager apps to tell app_args list to clients of app_manager. So client interface of app_args to a user have to be implemented to express a dictionary which has strings as values and has strings as keys. (I know my implementation is more ambiguous than this.)
And KeyValue message definition comes from roslaunch's args specification. They do not have types and limitations for arg values.
In order to add types and value ranges to app args, we need to re-consider app_args interface of app_manager's apps.

**Comment by Affonso-Gui** [comment]
I do think that this is a good pretext for reconsidering the app_args interface (adding fields to list_apps message, or adding another channel of communication?)

**Comment by Affonso-Gui** [comment]
@knorth55

**Comment by k-okada** [comment]
@sktometometo please fix test

**Comment by sktometometo** [comment]
@k-okada CI passed

**Pull request merged**
