### PR TITLE
rwt_app_chooser: fix typo in README.md

### PR DESCRIPTION
**Pull request by furushchev**
Mentioned at https://github.com/tork-a/visualization_rwt/pull/67#pullrequestreview-87725817

### CODE REVIEW

**Comment by k-okada** [comment]
still not working.... I'm using Google Chrome Version 61.0.3163.100 (Official Build) (64-bit), I had
````
WARNING:tornado.access:404 GET /3rdparty/phonon/css/phonon.css (127.0.0.1) 0.79ms
WARNING:tornado.access:404 GET /css/rwt_app_chooser.css (127.0.0.1) 0.85ms
WARNING:tornado.access:404 GET /3rdparty/store/js/store.everything.min.js (127.0.0.1) 0.88ms
WARNING:tornado.access:404 GET /3rdparty/phonon/js/phonon.js (127.0.0.1) 0.95ms
WARNING:tornado.access:404 GET /3rdparty/ros/js/eventemitter2.js (127.0.0.1) 2.00ms
WARNING:tornado.access:404 GET /3rdparty/ros/js/roslib.js (127.0.0.1) 1.18ms
WARNING:tornado.access:404 GET /js/rwt_app_chooser.js (127.0.0.1) 1.43ms
WARNING:tornado.access:404 GET /js/index.js (127.0.0.1) 1.04ms
````
after changing 
```
diff --git a/rwt_app_chooser/www/index.html b/rwt_app_chooser/www/index.html
index 1c36d45..45bce89 100644
--- a/rwt_app_chooser/www/index.html
+++ b/rwt_app_chooser/www/index.html
@@ -6,8 +6,8 @@
     <meta name="viewport" content="user-scalable=no,initial-scale=1,maximum-scale=1,minimum-scale=1,width=device-width,height=device-height" />
 
     <!-- CSS -->
-    <link href="3rdparty/phonon/css/phonon.css" rel="stylesheet">
-    <link href="css/rwt_app_chooser.css" rel="stylesheet">
+    <link href="/rwt_app_chooser/3rdparty/phonon/css/phonon.css" rel="stylesheet">
+    <link href="/rwt_app_chooser/css/rwt_app_chooser.css" rel="stylesheet">
   </head>
   <body>
     <!-- Components -->
@@ -16,11 +16,11 @@
     <task data-page="true"></task>
 
     <!-- Javascript -->
-    <script src="3rdparty/store/js/store.everything.min.js"></script>
-    <script src="3rdparty/phonon/js/phonon.js"></script>
-    <script src="3rdparty/ros/js/eventemitter2.js"></script>
-    <script src="3rdparty/ros/js/roslib.js"></script>
-    <script src="js/rwt_app_chooser.js"></script>
-    <script src="js/index.js"></script>
+    <script src="/rwt_app_chooser/3rdparty/store/js/store.everything.min.js"></script>
+    <script src="/rwt_app_chooser/3rdparty/phonon/js/phonon.js"></script>
+    <script src="/rwt_app_chooser/3rdparty/ros/js/eventemitter2.js"></script>
+    <script src="/rwt_app_chooser/3rdparty/ros/js/roslib.js"></script>
+    <script src="/rwt_app_chooser/js/rwt_app_chooser.js"></script>
+    <script src="/rwt_app_chooser/js/index.js"></script>
   </body>
 </html>
diff --git a/rwt_app_chooser/www/js/index.js b/rwt_app_chooser/www/js/index.js
index 9cb33c4..8592176 100644
--- a/rwt_app_chooser/www/js/index.js
+++ b/rwt_app_chooser/www/js/index.js
@@ -2,7 +2,7 @@ phonon.options({
   navigator: {
     defaultPage: 'robot',
     animatePages: true,
-    templateRootDirectory: 'components/',
+    templateRootDirectory: '/rwt_app_chooser/components/',
     enableBrowserBackButton: true,
   },
   i18n: null
```
I can see index.html, and it says 'Please add your robot to this list!', but both 'ADD A ROBOT' and 'CLEAR' button are not working.

**Comment by furushchev** [comment]
@k-okada Strange... It now works on my computer without any complain from `roswww`:

```bash
done
furushchev@ease:~/ros/indigo/src/tork-a/visualization_rwt/rwt_app_chooser$ roslaunch rwt_app_chooser rwt_app_chooser.launch 
... logging to /home/furushchev/.ros/log/596c3510-f5bb-11e7-bb80-a0369f3f4d96/roslaunch-ease-23553.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://133.11.216.222:38215/

SUMMARY
========

PARAMETERS
 * /rosdistro: indigo
 * /rosversion: 1.11.21

NODES
  /
    roswww (roswww/webserver.py)

ROS_MASTER_URI=http://localhost:11311

core service [/rosout] found
process[roswww-1]: started with pid [23574]
2018-01-10 13:04:58,659 - roswww - INFO - roswww : # of packages : 738
2018-01-10 13:04:58,660 - roswww - INFO - roswww : Weg Page root : www
2018-01-10 13:04:58,828 - roswww - INFO - roswww : Initialised
2018-01-10 13:04:58,828 - roswww - INFO - roswww : Attempting to start webserver on port 8000
2018-01-10 13:04:58,831 - roswww - INFO - roswww : Webserver successfully started on port 8000
WARNING:tornado.access:404 GET /favicon.ico (::1) 2.20ms
```

```bash
furushchev@ease:~/ros/indigo/src/tork-a/visualization_rwt/rwt_app_chooser$ rosparam set robot/type pr2
furushchev@ease:~/ros/indigo/src/tork-a/visualization_rwt/rwt_app_chooser$ rosparam set robot/name pr1012
furushchev@ease:~/ros/indigo/src/tork-a/visualization_rwt/rwt_app_chooser$ roslaunch rwt_app_chooser app_manager.launch 
... logging to /home/furushchev/.ros/log/596c3510-f5bb-11e7-bb80-a0369f3f4d96/roslaunch-ease-23409.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://ease:35820/

SUMMARY
========

PARAMETERS
 * /app_manager/interface_master: http://localhost:...
 * /rosbridge_websocket/address: 
 * /rosbridge_websocket/authenticate: False
 * /rosbridge_websocket/delay_between_messages: 0
 * /rosbridge_websocket/fragment_timeout: 600
 * /rosbridge_websocket/max_message_size: None
 * /rosbridge_websocket/port: 9090
 * /rosbridge_websocket/retry_startup_delay: 5
 * /rosdistro: indigo
 * /rosversion: 1.11.21

NODES
  /
    app_manager (app_manager/app_manager)
    appmaster (app_manager/appmaster)
    rosapi (rosapi/rosapi_node)
    rosbridge_websocket (rosbridge_server/rosbridge_websocket)

ROS_MASTER_URI=http://localhost:11311

core service [/rosout] found
process[appmaster-1]: started with pid [23442]
process[app_manager-2]: started with pid [23443]
process[rosbridge_websocket-3]: started with pid [23444]
process[rosapi-4]: started with pid [23445]
registered capabilities (classes):
 - rosbridge_library.capabilities.call_service.CallService
 - rosbridge_library.capabilities.advertise.Advertise
 - rosbridge_library.capabilities.publish.Publish
 - rosbridge_library.capabilities.subscribe.Subscribe
 - <class 'rosbridge_library.capabilities.defragmentation.Defragment'>
 - rosbridge_library.capabilities.advertise_service.AdvertiseService
 - rosbridge_library.capabilities.service_response.ServiceResponse
 - rosbridge_library.capabilities.unadvertise_service.UnadvertiseService
[INFO] [WallTime: 1515557091.425997] Rosbridge WebSocket server started on port 9090
apps.installed
loading installation data for [apps.installed]
[INFO] [WallTime: 1515557093.399629] Starting app manager for pr1012
/home/furushchev/ros/indigo/src/PR2/app_manager/src/app_manager/app_manager.py:66: SyntaxWarning: The publisher should be created with an explicit keyword argument 'queue_size'. Please see http://wiki.ros.org/rospy/Overview/Publishers%20and%20Subscribers for more information.
  self._status_pub = rospy.Publisher(self.scoped_name('application/app_status'), AppStatus, latch=True)
/home/furushchev/ros/indigo/src/PR2/app_manager/src/app_manager/app_manager.py:67: SyntaxWarning: The publisher should be created with an explicit keyword argument 'queue_size'. Please see http://wiki.ros.org/rospy/Overview/Publishers%20and%20Subscribers for more information.
  self._list_apps_pub = rospy.Publisher(self.scoped_name('app_list'), AppList, latch=True)
[INFO] [WallTime: 1515557093.409849] Waiting for foreign master [http://localhost:11312] to come up...
[INFO] [WallTime: 1515557093.412622] Foreign master is available
[INFO] [WallTime: 1515557093.438977] Registering (/pr1012/app_list,http://ease:41717/) on master http://localhost:11312
[INFO] [WallTime: 1515557093.443272] Registering (/pr1012/application/app_status,http://ease:41717/) on master http://localhost:11312
apps.installed
[INFO] [WallTime: 1515557093.447393] Registering service (/pr1012/list_apps,rosrpc://ease:43408) on master http://localhost:11312
[INFO] [WallTime: 1515557093.450150] Registering service (/pr1012/start_app,rosrpc://ease:43408) on master http://localhost:11312
[INFO] [WallTime: 1515557093.453116] Registering service (/pr1012/stop_app,rosrpc://ease:43408) on master http://localhost:11312
[INFO] [WallTime: 1515557131.775774] Client connected.  1 clients total.
[INFO] [WallTime: 1515557132.302570] [Client 0] Subscribed to /pr1012/app_list
```

sc
sc2

**Comment by furushchev** [comment]
@k-okada Ah, guessing you accessed `http://localhost:8000/rwt_app_chooser`!
Could you try again to access to `http://localhost:8000/rwt_app_chooser/` ( <- ends with `/`)

**Comment by furushchev** [comment]
Updated README again. Sorry for inconvenience.

**Comment by k-okada** [comment]
thank you, I can connect to web page without changing source code, but still could not see robot/app list.
I can not find
```
[INFO] [WallTime: 1515557131.775774] Client connected.  1 clients total.
[INFO] [WallTime: 1515557132.302570] [Client 0] Subscribed to /pr1012/app_list
```
in my terminal I can see client connected

**Comment by furushchev** [comment]
@k-okada Hmm, let me check: you already added a robot type PR2 and looked icon of PR2 instead of a text 'Please add your robot to this list', and then pressed the robot icon but no launcher icons show up, right?

**Pull request merged**
