### PR TITLE
rwt_map added

### PR DESCRIPTION
**Pull request by YugAjmera**
Adding the webui to control the robot using joystick and camera feed and visualize the map being built

### CODE REVIEW

**Review by k-okada — COMMENTED** [review]
very nice, can we add features like
- move, zoom rotate the map
- display occupancy grids
- display local global paths
- display robot pose

also can we add buttons to set current and goal pose of the robot?

if these features are planned to include in different modules, such as rwt_nav_view, then it is ok.

**Comment by YugAjmera** [comment]
I will add following features : 
- [x] Pan
- [x] Zoom
- [x] Display robot`s current position on map
- [ ] Saving the map built.

And yes, I have planned to add the other features in rwt_nav application.

**Comment by YugAjmera** [comment]
I will open a new pull request once the project is fully complete

**Comment by YugAjmera** [comment]
Shifted to #89

**Pull request closed without merging**
