### PR TITLE
Add settings for deploy as GitHub Pages

### PR DESCRIPTION
**Pull request by furushchev**
This is for adding deploy procedure to GitHub Pages.

To admin, you will have to do 2 procedures for deployment to github pages:

1. Set `GH_TOKEN` with push access to travis (via [Web GUI](https://travis-ci.org/tork-a/visualization_rwt/settings))
  
  travis-env

2. Enable Github Pages on [Settings](https://github.com/tork-a/visualization_rwt)
  Select `master branch` for source.
  It should look like below:  
  githubpages

### CODE REVIEW

**Comment by furushchev** [comment]
@k-okada Thank you for merging! Are you using custom url? If not, public url will be https://tork-a.github.io/visualization_rwt/ .

**Comment by k-okada** [comment]
sorry for late, done https://tork-a.github.io/visualization_rwt/
I prefer to push doc to gh-pages and hide these files from normal users.

--
◉ Kei Okada


2018-01-22 17:31 GMT+09:00 Furushchev <notifications@github.com>:

**Comment by furushchev** [comment]
@k-okada Great! Thanks! I also prefer it to pushing to master branch, but it looks there is no more such an option.

pages

https://stackoverflow.com/questions/31439951/how-can-i-use-a-branch-other-than-master-for-user-github-pages

**Comment by furushchev** [comment]
(You may already know but) The default branch is configurable, it might be a workaround...

branch

**Comment by k-okada** [comment]
?? I changed to push doc to go-pages, and i’m ok with this. https://github.com/tork-a/visualization_rwt/commits/gh-pages
I want to hide this from normal uses, which means those who just clone the default branch do not have to see this commit

**Pull request merged**
