### PR TITLE
publish confidences; fix message type texts -> transcript

### PR DESCRIPTION
**Pull request by furushchev**

### CODE REVIEW

**Comment by k-okada** [comment]
@umoji https://github.com/tork-a/visualization_rwt/tree/hydro-devel/
Is what you're looking for

We need https://github.com/RobotWebTools/rosbridge_suite/pull/158 at this moment

**Comment by umoji** [comment]
Thanks to jsk's members, I already solved this probrem yesterday by subscribing /Tablet/voice.
But 

```
$ rostopic echo /Tablet/voice
```

can recognize only English.
How can I recognize Japanese?

**Comment by furushchev** [comment]
You can choose language from "Language" Tab on the web page.
Currently, Japanese, English and Russian are available.

**Comment by umoji** [comment]
Recognition was successful, and I could see Japanese and English on the web.
But on terminal, Japanese words didn't display.
Is this because of the choice of language on the web?

```
rostopic echo /Tablet/voice
texts: ['\xe3\x81\x93\xe3\x82\x93\xe3\x81\xab\xe3\x81\xa1\xe3\x81\xaf', '\xe3\x81\x93\xe3\x82\x93\xe3\x81\xab\xe3\x81\xa1\xe3\x82\x8f', '\xe3\x82\xb3\xe3\x83\xb3\xe3\x83\x8b\xe3\x83\x81\xe3\x83\xaf']
---
texts: [' \xe3\x81\x93\xe3\x82\x93\xe3\x81\xab\xe3\x81\xa1\xe3\x81\xaf', ' \xe3\x81\x93\xe3\x82\x93\xe3\x81\xab\xe3\x81\xa1\xe3\x82\x8f', ' \xe3\x82\xb3\xe3\x83\xb3\xe3\x83\x8b\xe3\x83\x81\xe3\x83\xaf']
---
texts: [' \xe3\x81\x8a\xe3\x81\xaf\xe3\x82\x88\xe3\x81\x86', ' \xe3\x81\x8a\xe3\x81\xaf\xe3\x82\x88', ' \xe3\x81\x8a\xe3\x81\xaf\xe3\x82\x88\xe3\x81\x86\xe5\xa0\x82', ' \xe3\x81\x8a\xe3\x81\xaf\xe3\x82\x88\xe3\x81\x86 \xe6\xad\x8c', ' \xe3\x81\x8a\xe3\x81\xaf\xe3\x82\x88\xe3\x81\x86\xe3\x81\xa3\xe3\x81\xa6']
---
texts: [' \xe3\x82\x80\xe3\x81\x8b\xe3\x81\x97\xe3\x82\x80\xe3\x81\x8b\xe3\x81\x97\xe3\x81\x82\xe3\x82\x8b\xe3\x81\xa8\xe3\x81\x93\xe3\x82\x8d\xe3\x81\xab', ' \xe3\x82\x80\xe3\x81\x8b\xe3\x81\x97\xe3\x82\x80\xe3\x81\x8b\xe3\x81\x97 \xe3\x81\x82\xe3\x82\x8b\xe3\x81\xa8\xe3\x81\x93\xe3\x82\x8d\xe3\x81\xab', ' \xe6\x98\x94\xe3\x82\x80\xe3\x81\x8b\xe3\x81\x97 \xe3\x81\x82\xe3\x82\x8b\xe3\x81\xa8\xe3\x81\x93\xe3\x82\x8d\xe3\x81\xab', ' \xe3\x82\x80\xe3\x81\x8b\xe3\x81\x97\xe3\x82\x80\xe3\x81\x8b\xe3\x81\x97 \xe3\x82\xa2\xe3\x83\xab\xe3\x83\x88\xe3\x82\xb3\xe3\x83\xad\xe3\x83\x8b\xe3\x83\xbc', ' \xe3\x82\x80\xe3\x81\x8b\xe3\x81\x97\xe3\x82\x80\xe3\x81\x8b\xe3\x81\x97 \xe3\x81\x82\xe3\x82\x8b\xe3\x81\xa8\xe3\x81\x93\xe3\x82\x8d\xe3\x81\xab\xe3\x83\xbc']
---
texts: [' hello', ' \xe3\x83\x8f\xe3\x83\xad\xe3\x83\xbc', ' halo', ' \xe3\x83\x98\xe3\x83\xad\xe3\x83\xbc']
---
texts: [' myname', ' my name', ' \xe3\x83\x9e\xe3\x82\xa4\xe3\x83\x8d\xe3\x83\xbc\xe3\x83\xa0', ' \xe3\x81\xbe\xe3\x81\x84\xe3\x81\xad\xe3\x83\xbc\xe3\x82\x80']
---
texts: [' \xe3\x82\xb0\xe3\x83\x83\xe3\x83\xa2\xe3\x83\xbc\xe3\x83\x8b\xe3\x83\xb3', ' \xe3\x82\xb0\xe3\x83\x83\xe3\x83\x89\xe3\x83\xa2\xe3\x83\xbc\xe3\x83\x8b\xe3\x83\xb3\xe3\x82\xb0', ' good morning', ' \xe3\x83\xa2\xe3\x83\xbc\xe3\x83\x8b\xe3\x83\xb3\xe3\x82\xb0']
---
texts: [' \xe6\x97\xa5\xe6\x9c\xac 123', ' \xe6\x97\xa5\xe6\x9c\xac\xe8\xaa\x9e 123', ' \xe6\x97\xa5\xe6\x9c\xac\xe3\x82\x92\xe3\x83\x80\xe3\x83\xa1\xe3\x81\xa7\xe3\x81\x99\xe3\x81\xad 123', ' \xe6\x97\xa5\xe6\x9c\xac 3 4 1 2 3', ' \xe6\x97\xa5\xe6\x9c\xac\xe8\xaa\x9e 1 2 3']
---
```

**Comment by furushchev** [comment]
This is just such a display of rostopic.
Please check if the contents is Japanese in your program.

**Comment by umoji** [comment]
In my program, Japanese was detected successfuly.
Thank you.

**Comment by furushchev** [comment]
According to the discussion at RobotWebTools/rosbridge_suite#158 , I should fix my code.
After merging https://github.com/tork-a/visualization_rwt/pull/49 , this package works fine in hydro, I think.

**Comment by k-okada** [comment]
Thanks, Discussion is always bring us a good solution. ;-)

## 

◉ Kei Okada

**Comment by 130s** [comment]
@furushchev @umoji any +1s?

**Comment by furushchev** [comment]
@130s Sorry, I don't understand what you mean.

**Comment by 130s** [comment]
Sorry!
Is this good to merge (Just give "+1" if it is)?

**Comment by furushchev** [comment]
:+1:

**Pull request merged**
