### PR TITLE
Add rwt speech recognition

### PR DESCRIPTION
**Pull request by furushchev**
rwt_speech_recognition package is a speech-to-text web application using Web Speech API ( https://dvcs.w3.org/hg/speech-api/raw-file/tip/speechapi.html )

Former name "rwt_voice_message" is not so much used, so I renamed name to rwt_speech_recognition along with API name.

Also note that this is currently not supported confidences because of also not good support of browsers.

### CODE REVIEW

**Comment by furushchev** [comment]
This is formerly mentioned at https://github.com/tork-a/visualization_rwt/pull/23

**Comment by garaemon** [comment]
travis failed

**Comment by furushchev** [comment]
> travis failed

I think it is another problem.

**Comment by garaemon** [comment]
i see, it comes from rwt_plot

**Comment by garaemon** [comment]
@k-okada could you merge this PR?

**Comment by k-okada** [comment]
merged

**Pull request merged**
